---
title: "model test norm mask used"
author: "Christopher Soria"
date: "2023-11-21"
output: html_document
---
```{r}
library(dplyr)
library(tidyverse)
library(pscl)
library(car)
library(data.table)
library(MASS)
```


```{r}
df <- fread("/Users/chrissoria/Documents/Research/BICS_Political_Polarization/data/BICS_ZIP_Features.csv")
RD_df <- df[df$political_party %in% c("Republican", "Democrat"), ]
D_df <- df[df$political_party == "Democrat"]
R_df <- df[df$political_party == "Republican"]

names(df) <- make.unique(names(df))
names(RD_df) <- make.unique(names(RD_df))
names(D_df) <- make.unique(names(D_df))
names(R_df) <- make.unique(names(R_df))
```


```{r}
D_model_anova <- aov(Norm_Masks_Used ~ as.factor(Percentage_Trump_Greater_Than_Two_Thirds) + COV_County_CMR_2020_06_20 +
                     State_Government_Response_Index_11192020 + COUNTY_RUCC_2013 + resp_sex +
                     resp_educ + resp_yob + r_working + r_race, data = D_df)

R_model_anova <- aov(Norm_Masks_Used ~ as.factor(Percentage_Biden_Greater_Than_Two_Thirds) + COV_County_CMR_2020_06_20 +
                     State_Government_Response_Index_11192020 + COUNTY_RUCC_2013 + resp_sex +
                     resp_educ + resp_yob + r_working + r_race, data = R_df)

# Print the results
summary(D_model_anova)
summary(R_model_anova)
```

