---
title: "three-group-sir"
author: "Christopher Soria"
date: "2024-06-09"
output: html_document
---
data to be removed
```{r}
library(deSolve)
```

```{r}
sf_df <- subset(bics_zip_features, city == "Bay Area")
pho_df <- subset(bics_zip_features, city == "Phoenix")
```


defining the function
```{r}
sir_three_group_pu <- function(c = NA, # average number of contacts per day (specify only if its the same for all groups, otherwise NA)
                               c_a = 3, c_b = 3, c_c = 3, # average number of contacts per day by group
                               trans_p = 0.05, # probability of transmission given contact
                               rho = 1/10, # 1 / infectious period or recovery rate
                               mu = 0.01, # probability of dying following infection
                               h_a = 0.5, h_b = 0.5, # proportions of each group's total contact with members of their own group
                               kappa = 0.03, # reduction in probability of transmission given contact resulting from protective behavior
                               phi = 0, # waning of protective behavior
                               I0_a = 1, I0_b = 1, I0_c = 1, # initial infected in each group
                               N0 = 10000000, # population size
                               frac_a = 0.33, frac_b = 0.33, # fractions of population in groups A and B
                               time = 500, # time steps for simulation
                               ell = 1, # time window for considering deaths that influence adoption of protective behavior
                               theta = NA, # responsiveness to deaths for adopting protective behavior
                               theta_a = 100, theta_b = 100, theta_c = 100,
                               epsilon = NA, # measure of assortativeness in influence
                               epsilon_a = 0.5, epsilon_b = 0.5, epsilon_c = 0.5,
                               omega = NA, # responsiveness to proportion of protected individuals for adopting protective behavior
                               omega_a = 0.1, omega_b = 0.1, omega_c = 0.1,
                               get_params = FALSE) {
  
  if (!is.na(epsilon)) {  
    epsilon_a <- epsilon  
    epsilon_b <- epsilon
    epsilon_c <- epsilon
  }
  
  if (!is.na(theta)) {   
    theta_a <- theta
    theta_b <- theta
    theta_c <- theta
  }
  
  if (!is.na(omega)) {  
    omega_a <- omega
    omega_b <- omega
    omega_c <- omega
  }
  
  if (!is.na(c)) {  
    c_a <- c
    c_b <- c
    c_c <- c
  }
  
  N0_a = N0 * frac_a
  N0_b = N0 * frac_b
  N0_c = N0 * (1 - frac_a - frac_b)
  
  C_a = c_a * N0_a
  C_b = c_b * N0_b
  C_c = c_c * N0_c
  
  if (C_a * (1 - h_a) < C_b) {
    C_ba = C_ab = C_a * (1 - h_a)
  } else {
    C_ba = C_ab = C_b
  }
  
  if (C_b * (1 - h_b) < C_c) {
    C_cb = C_bc = C_b * (1 - h_b)
  } else {
    C_cb = C_bc = C_c
  }
  
  C_aa = C_a - C_ba
  C_bb = C_b - C_ab
  C_cc = C_c - C_bc
  C_ac = C_c - C_cb
  C_ca = C_a - C_ab
  
  c_aa = C_aa / N0_a
  c_ba = C_ba / N0_a
  c_ab = C_ab / N0_b
  c_bb = C_bb / N0_b
  c_bc = C_bc / N0_b
  c_cb = C_cb / N0_c
  c_cc = C_cc / N0_c
  c_ac = C_ac / N0_c
  c_ca = C_ca / N0_a
  
  N_a = N0_a
  N_b = N0_b
  N_c = N0_c
  
  params <- c("trans_p" = trans_p,
              "h_a" = h_a, "h_b" = h_b,
              "c_a" = c_a, "c_b" = c_b, "c_c" = c_c,
              "c_aa" = c_aa, "c_ab" = c_ab, "c_ac" = c_ac,
              "c_ba" = c_ba, "c_bb" = c_bb, "c_bc" = c_bc,
              "c_ca" = c_ca, "c_cb" = c_cb, "c_cc" = c_cc,
              "kappa" = kappa,
              "phi" = phi,
              "rho" = rho,
              "mu" = mu,
              "time" = time,
              "I0_a" = I0_a, "I0_b" = I0_b, "I0_c" = I0_c,
              "N0_a" = N0_a, "N0_b" = N0_b, "N0_c" = N0_c,
              "ell" = ell,
              "epsilon_a" = epsilon_a, "epsilon_b" = epsilon_b, "epsilon_c" = epsilon_c,
              "theta_a" = theta_a, "theta_b" = theta_b, "theta_c" = theta_c,
              "omega_a" = omega_a, "omega_b" = omega_b, "omega_c" = omega_c)
  
  state <- c(
    # group a
    SUa = (N0_a - I0_a), SPa = 0, IUa = I0_a, IPa = 0, RUa = 0, RPa = 0, DUa = 0, DPa = 0,
    # group b
    SUb = (N0_b - I0_b), SPb = 0, IUb = I0_b, IPb = 0, RUb = 0, RPb = 0, DUb = 0, DPb = 0,
    # group c
    SUc = (N0_c - I0_c), SPc = 0, IUc = I0_c, IPc = 0, RUc = 0, RPc = 0, DUc = 0, DPc = 0
  )
  
  names(state) <- c("SUa", "SPa", "IUa", "IPa", "RUa", "RPa", "DUa", "DPa",
                    "SUb", "SPb", "IUb", "IPb", "RUb", "RPb", "DUb", "DPb",
                    "SUc", "SPc", "IUc", "IPc", "RUc", "RPc", "DUc", "DPc")
  
  sir_up <- function(t, state, parameter) {
    with(as.list(c(parameter, state)), {
      if (t < ell) {
        lag <- rep(0, length(state))
      } else {
        lag <- lagvalue(t - ell)
      }
      
      # Transitions for group A
      dSUa <- -SUa * trans_p * (c_aa * (IUa / N_a + kappa * IPa / N_a) +
                                c_ba * (IUb / N_b + kappa * IPb / N_b) +
                                c_ca * (IUc / N_c + kappa * IPc / N_c)) +
        phi * SPa -
        theta_a * SUa * (epsilon_a * ((DUa + DPa - lag[which(names(state) == "DUa")] - lag[which(names(state) == "DPa")]) / N_a) +
                         (1 - epsilon_a) * ((DUb + DPb - lag[which(names(state) == "DUb")] - lag[which(names(state) == "DPb")]) / N_b +
                                            (DUc + DPc - lag[which(names(state) == "DUc")] - lag[which(names(state) == "DPc")]) / N_c)) -
        omega_a * SUa * (epsilon_a * ((SPa + IPa + RPa) / N_a) + 
                         (1 - epsilon_a) * ((SPb + IPb + RPb) / N_b + (SPc + IPc + RPc) / N_c))
      
      dSPa <- -SPa * kappa * trans_p * (c_aa * (IUa / N_a + kappa * IPa / N_a) +
                                        c_ba * (IUb / N_b + kappa * IPb / N_b) +
                                        c_ca * (IUc / N_c + kappa * IPc / N_c)) -
        phi * SPa +
        theta_a * SUa * (epsilon_a * ((DUa + DPa - lag[which(names(state) == "DUa")] - lag[which(names(state) == "DPa")]) / N_a) +
                                       (1 - epsilon_a) * ((DUb + DPb - lag[which(names(state) == "DUb")] - lag[which(names(state) == "DPb")]) / N_b +
                                                          (DUc + DPc - lag[which(names(state) == "DUc")] - lag[which(names(state) == "DPc")]) / N_c)) +
        omega_a * SUa * (epsilon_a * ((SPa + IPa + RPa) / N_a) + 
                         (1 - epsilon_a) * ((SPb + IPb + RPb) / N_b + (SPc + IPc + RPc) / N_c))
      
      dIUa <- SUa * trans_p * (c_aa * (IUa / N_a + kappa * IPa / N_a) +
                               c_ba * (IUb / N_b + kappa * IPb / N_b) +
                               c_ca * (IUc / N_c + kappa * IPc / N_c)) +
        phi * IPa -
        rho * IUa -
        theta_a * IUa * (epsilon_a * ((DUa + DPa - lag[which(names(state) == "DUa")] - lag[which(names(state) == "DPa")]) / N_a) +
                         (1 - epsilon_a) * ((DUb + DPb - lag[which(names(state) == "DUb")] - lag[which(names(state) == "DPb")]) / N_b +
                                            (DUc + DPc - lag[which(names(state) == "DUc")] - lag[which(names(state) == "DPc")]) / N_c)) -
        omega_a * IUa * (epsilon_a * ((SPa + IPa + RPa) / N_a) + 
                         (1 - epsilon_a) * ((SPb + IPb + RPb) / N_b + (SPc + IPc + RPc) / N_c))
      
      dIPa <- SPa * trans_p * kappa * (c_aa * (IUa / N_a + kappa * IPa / N_a) +
                                       c_ba * (IUb / N_b + kappa * IPb / N_b) +
                                       c_ca * (IUc / N_c + kappa * IPc / N_c)) -
        phi * IPa -
        rho * IPa +
        theta_a * IUa * (epsilon_a * ((DUa + DPa - lag[which(names(state) == "DUa")] - lag[which(names(state) == "DPa")]) / N_a) +
                         (1 - epsilon_a) * ((DUb + DPb - lag[which(names(state) == "DUb")] - lag[which(names(state) == "DPb")]) / N_b +
                                            (DUc + DPc - lag[which(names(state) == "DUc")] - lag[which(names(state) == "DPc")]) / N_c)) +
        omega_a * IUa * (epsilon_a * ((SPa + IPa + RPa) / N_a) + 
                         (1 - epsilon_a) * ((SPb + IPb + RPb) / N_b + (SPc + IPc + RPc) / N_c))
      
      dRUa <- rho * (1 - mu) * IUa + phi * RPa -
        theta_a * RUa * (epsilon_a * ((DUa + DPa - lag[which(names(state) == "DUa")] - lag[which(names(state) == "DPa")]) / N_a) +
                         (1 - epsilon_a) * ((DUb + DPb - lag[which(names(state) == "DUb")] - lag[which(names(state) == "DPb")]) / N_b +
                                            (DUc + DPc - lag[which(names(state) == "DUc")] - lag[which(names(state) == "DPc")]) / N_c)) -
        omega_a * RUa * (epsilon_a * ((SPa + IPa + RPa) / N_a) + 
                         (1 - epsilon_a) * ((SPb + IPb + RPb) / N_b + (SPc + IPc + RPc) / N_c))
      
      dRPa <- rho * (1 - mu) * IPa - phi * RPa +
        theta_a * RUa * (epsilon_a * ((DUa + DPa - lag[which(names(state) == "DUa")] - lag[which(names(state) == "DPa")]) / N_a) +
                         (1 - epsilon_a) * ((DUb + DPb - lag[which(names(state) == "DUb")] - lag[which(names(state) == "DPb")]) / N_b +
                                            (DUc + DPc - lag[which(names(state) == "DUc")] - lag[which(names(state) == "DPc")]) / N_c)) +
        omega_a * RUa * (epsilon_a * ((SPa + IPa + RPa) / N_a) + 
                         (1 - epsilon_a) * ((SPb + IPb + RPb) / N_b + (SPc + IPc + RPc) / N_c))
      
      dDUa <- rho * mu * IUa
      
      dDPa <- rho * mu * IPa
      
      # Transitions for group B
      dSUb <- -SUb * trans_p * (c_ab * (IUa / N_a + kappa * IPa / N_a) +
                                c_bb * (IUb / N_b + kappa * IPb / N_b) +
                                c_cb * (IUc / N_c + kappa * IPc / N_c)) +
        phi * SPb -
        theta_b * SUb * (epsilon_b * ((DUb + DPb - lag[which(names(state) == "DUb")] - lag[which(names(state) == "DPb")]) / N_b) +
                         (1 - epsilon_b) * ((DUa + DPa - lag[which(names(state) == "DUa")] - lag[which(names(state) == "DPa")]) / N_a +
                                            (DUc + DPc - lag[which(names(state) == "DUc")] - lag[which(names(state) == "DPc")]) / N_c)) -
        omega_b * SUb * (epsilon_b * ((SPb + IPb + RPb) / N_b) + 
                         (1 - epsilon_b) * ((SPa + IPa + RPa) / N_a + (SPc + IPc + RPc) / N_c))
      
      dSPb <- -SPb * kappa * trans_p * (c_ab * (IUa / N_a + kappa * IPa / N_a) +
                                        c_bb * (IUb / N_b + kappa * IPb / N_b) +
                                        c_cb * (IUc / N_c + kappa * IPc / N_c)) -
        phi * SPb +
        theta_b * SUb * (epsilon_b * ((DUb + DPb - lag[which(names(state) == "DUb")] - lag[which(names(state) == "DPb")]) / N_b) +
                         (1 - epsilon_b) * ((DUa + DPa - lag[which(names(state) == "DUa")] - lag[which(names(state) == "DPa")]) / N_a +
                                            (DUc + DPc - lag[which(names(state) == "DUc")] - lag[which(names(state) == "DPc")]) / N_c)) +
        omega_b * SUb * (epsilon_b * ((SPb + IPb + RPb) / N_b) + 
                         (1 - epsilon_b) * ((SPa + IPa + RPa) / N_a + (SPc + IPc + RPc) / N_c))
      
      dIUb <- SUb * trans_p * (c_ab * (IUa / N_a + kappa * IPa / N_a) +
                               c_bb * (IUb / N_b + kappa * IPb / N_b) +
                               c_cb * (IUc / N_c + kappa * IPc / N_c)) +
        phi * IPb -
        rho * IUb -
        theta_b * IUb * (epsilon_b * ((DUb + DPb - lag[which(names(state) == "DUb")] - lag[which(names(state) == "DPb")]) / N_b) +
                         (1 - epsilon_b) * ((DUa + DPa - lag[which(names(state) == "DUa")] - lag[which(names(state) == "DPa")]) / N_a +
                                            (DUc + DPc - lag[which(names(state) == "DUc")] - lag[which(names(state) == "DPc")]) / N_c)) -
                omega_b * IUb * (epsilon_b * ((SPb + IPb + RPb) / N_b) + 
                         (1 - epsilon_b) * ((SPa + IPa + RPa) / N_a + (SPc + IPc + RPc) / N_c))
      
      dIPb <- SPb * trans_p * kappa * (c_ab * (IUa / N_a + kappa * IPa / N_a) +
                                       c_bb * (IUb / N_b + kappa * IPb / N_b) +
                                       c_cb * (IUc / N_c + kappa * IPc / N_c)) -
        phi * IPb -
        rho * IPb +
        theta_b * IUb * (epsilon_b * ((DUb + DPb - lag[which(names(state) == "DUb")] - lag[which(names(state) == "DPb")]) / N_b) +
                         (1 - epsilon_b) * ((DUa + DPa - lag[which(names(state) == "DUa")] - lag[which(names(state) == "DPa")]) / N_a +
                                            (DUc + DPc - lag[which(names(state) == "DUc")] - lag[which(names(state) == "DPc")]) / N_c)) +
        omega_b * IUb * (epsilon_b * ((SPb + IPb + RPb) / N_b) + 
                         (1 - epsilon_b) * ((SPa + IPa + RPa) / N_a + (SPc + IPc + RPc) / N_c))
      
      dRUb <- rho * (1 - mu) * IUb + phi * RPb -
        theta_b * RUb * (epsilon_b * ((DUb + DPb - lag[which(names(state) == "DUb")] - lag[which(names(state) == "DPb")]) / N_b) +
                         (1 - epsilon_b) * ((DUa + DPa - lag[which(names(state) == "DUa")] - lag[which(names(state) == "DPa")]) / N_a +
                                            (DUc + DPc - lag[which(names(state) == "DUc")] - lag[which(names(state) == "DPc")]) / N_c)) -
        omega_b * RUb * (epsilon_b * ((SPb + IPb + RPb) / N_b) + 
                         (1 - epsilon_b) * ((SPa + IPa + RPa) / N_a + (SPc + IPc + RPc) / N_c))
      
      dRPb <- rho * (1 - mu) * IPb - phi * RPb +
        theta_b * RUb * (epsilon_b * ((DUb + DPb - lag[which(names(state) == "DUb")] - lag[which(names(state) == "DPb")]) / N_b) +
                         (1 - epsilon_b) * ((DUa + DPa - lag[which(names(state) == "DUa")] - lag[which(names(state) == "DPa")]) / N_a +
                                            (DUc + DPc - lag[which(names(state) == "DUc")] - lag[which(names(state) == "DPc")]) / N_c)) +
        omega_b * RUb * (epsilon_b * ((SPb + IPb + RPb) / N_b) + 
                         (1 - epsilon_b) * ((SPa + IPa + RPa) / N_a + (SPc + IPc + RPc) / N_c))
      
      dDUb <- rho * mu * IUb
      
      dDPb <- rho * mu * IPb
      
      # Transitions for group C
      dSUc <- -SUc * trans_p * (c_ac * (IUa / N_a + kappa * IPa / N_a) +
                                c_bc * (IUb / N_b + kappa * IPb / N_b) +
                                c_cc * (IUc / N_c + kappa * IPc / N_c)) +
        phi * SPc -
        theta_c * SUc * (epsilon_c * ((DUc + DPc - lag[which(names(state) == "DUc")] - lag[which(names(state) == "DPc")]) / N_c) +
                         (1 - epsilon_c) * ((DUa + DPa - lag[which(names(state) == "DUa")] - lag[which(names(state) == "DPa")]) / N_a +
                                            (DUb + DPb - lag[which(names(state) == "DUb")] - lag[which(names(state) == "DPb")]) / N_b)) -
        omega_c * SUc * (epsilon_c * ((SPc + IPc + RPc) / N_c) + 
                         (1 - epsilon_c) * ((SPa + IPa + RPa) / N_a + (SPb + IPb + RPb) / N_b))
      
      dSPc <- -SPc * kappa * trans_p * (c_ac * (IUa / N_a + kappa * IPa / N_a) +
                                        c_bc * (IUb / N_b + kappa * IPb / N_b) +
                                        c_cc * (IUc / N_c + kappa * IPc / N_c)) -
        phi * SPc +
        theta_c * SUc * (epsilon_c * ((DUc + DPc - lag[which(names(state) == "DUc")] - lag[which(names(state) == "DPc")]) / N_c) +
                         (1 - epsilon_c) * ((DUa + DPa - lag[which(names(state) == "DUa")] - lag[which(names(state) == "DPa")]) / N_a +
                                            (DUb + DPb - lag[which(names(state) == "DUb")] - lag[which(names(state) == "DPb")]) / N_b)) +
        omega_c * SUc * (epsilon_c * ((SPc + IPc + RPc) / N_c) + 
                         (1 - epsilon_c) * ((SPa + IPa + RPa) / N_a + (SPb + IPb + RPb) / N_b))
      
      dIUc <- SUc * trans_p * (c_ac * (IUa / N_a + kappa * IPa / N_a) +
                               c_bc * (IUb / N_b + kappa * IPb / N_b) +
                               c_cc * (IUc / N_c + kappa * IPc / N_c)) +
        phi * IPc -
        rho * IUc -
        theta_c * IUc * (epsilon_c * ((DUc + DPc - lag[which(names(state) == "DUc")] - lag[which(names(state) == "DPc")]) / N_c) +
                         (1 - epsilon_c) * ((DUa + DPa - lag[which(names(state) == "DUa")] - lag[which(names(state) == "DPa")]) / N_a +
                                            (DUb + DPb - lag[which(names(state) == "DUb")] - lag[which(names(state) == "DPb")]) / N_b)) -
        omega_c * IUc * (epsilon_c * ((SPc + IPc + RPc) / N_c) + 
                         (1 - epsilon_c) * ((SPa + IPa + RPa) / N_a + (SPb + IPb + RPb) / N_b))
      
      dIPc <- SPc * trans_p * kappa * (c_ac * (IUa / N_a + kappa * IPa / N_a) +
                                       c_bc * (IUb / N_b + kappa * IPb / N_b) +
                                       c_cc * (IUc / N_c + kappa * IPc / N_c)) -
        phi * IPc -
        rho * IPc +
        theta_c * IUc * (epsilon_c * ((DUc + DPc - lag[which(names(state) == "DUc")] - lag[which(names(state) == "DPc")]) / N_c) +
                         (1 - epsilon_c) * ((DUa + DPa - lag[which(names(state) == "DUa")] - lag[which(names(state) == "DPa")]) / N_a +
                                            (DUb + DPb - lag[which(names(state) == "DUb")] - lag[which(names(state) == "DPb")]) / N_b)) +
        omega_c * IUc * (epsilon_c * ((SPc + IPc + RPc) / N_c) + 
                         (1 - epsilon_c) * ((SPa + IPa + RPa) / N_a + (SPb + IPb + RPb) / N_b))
      
      dRUc <- rho * (1 - mu) * IUc + phi * RPc -
        theta_c * RUc * (epsilon_c * ((DUc + DPc - lag[which(names(state) == "DUc")] - lag[which(names(state) == "DPc")]) / N_c) +
                         (1 - epsilon_c) * ((DUa + DPa - lag[which(names(state) == "DUa")] - lag[which(names(state) == "DPa")]) / N_a +
                                            (DUb + DPb - lag[which(names(state) == "DUb")] - lag[which(names(state) == "DPb")]) / N_b)) -
        omega_c * RUc * (epsilon_c * ((SPc + IPc + RPc) / N_c) + 
                         (1 - epsilon_c) * ((SPa + IPa + RPa) / N_a + (SPb + IPb + RPb) / N_b))
      
      dRPc <- rho * (1 - mu) * IPc - phi * RPc +
        theta_c * RUc * (epsilon_c * ((DUc + DPc - lag[which(names(state) == "DUc")] - lag[which(names(state) == "DPc")]) / N_c) +
                         (1 - epsilon_c) * ((DUa + DPa - lag[which(names(state) == "DUa")] - lag[which(names(state) == "DPa")]) / N_a +
                                            (DUb + DPb - lag[which(names(state) == "DUb")] - lag[which(names(state) == "DPb")]) / N_b)) +
        omega_c * RUc * (epsilon_c * ((SPc + IPc + RPc) / N_c) + 
                         (1 - epsilon_c) * ((SPa + IPa + RPa) / N_a + (SPb + IPb + RPb) / N_b))
      
      dDUc <- rho * mu * IUc
      
      dDPc <- rho * mu * IPc
      
      return(list(c(dSUa, dSPa, dIUa, dIPa, dRUa, dRPa, dDUa, dDPa,
                    dSUb, dSPb, dIUb, dIPb, dRUb, dRPb, dDUb, dDPb,
                    dSUc, dSPc, dIUc, dIPc, dRUc, dRPc, dDUc, dDPc)))
    })
  }
  
  times <- seq(from = 0, to = time, by = 1)
  
  as.data.frame(dede(state, times, sir_up, params)) -> sim
  
  if (get_params) {
    return(list(sim = sim, params = params))
  } else {
    return(sim)
  }
}
```

```{r}
prop_rep = weighted.mean(sf_df$republican, w = sf_df$weight_pooled, na.rm = TRUE)
print(prop_rep)

prop_dem = weighted.mean(sf_df$democrat, w = sf_df$weight_pooled, na.rm = TRUE)
print(prop_dem)

rep_cc <- sf_df %>%
  filter(republican == 1) %>%
  summarise(weighted_mean = weighted.mean(num_cc, w = weight_pooled, na.rm = TRUE)) %>%
  pull(weighted_mean)
print(paste("republicans had an average of", round(rep_cc, digits = 2), "ties"))

dem_cc <- sf_df %>%
  filter(democrat == 1) %>%
  summarise(weighted_mean = weighted.mean(num_cc, w = weight_pooled, na.rm = TRUE)) %>%
  pull(weighted_mean)
print(paste("democrats had an average of", round(dem_cc, digits = 2), "ties"))

ind_cc <- sf_df %>%
  filter(Independent == 1) %>%
  summarise(weighted_mean = weighted.mean(num_cc, w = weight_pooled, na.rm = TRUE)) %>%
  pull(weighted_mean)
print(paste("independents had an average of", round(ind_cc, digits = 2), "ties"))

N0 = 7753000

# Run the simulation
ls <- sir_three_group_pu(
  c = NA, 
  c_a = rep_cc, #republican contact rates
  c_b = dem_cc, #democrat contact rates
  c_c = ind_cc, #independent contact rates
  trans_p = 0.1, 
  rho = 1/14, 
  mu = 0.01, 
  h_a = 0.5, # proportion republican contact with members of their own group
  h_b = 0.5, # proportion democrat contact with members of their own group
  kappa = 0.3, 
  phi = 0.02, 
  I0_a = 1, # initial infected in republican group
  I0_b = 1, # initial infected in democrat group
  I0_c = 1, # initial infected in independent group
  N0 = N0, 
  frac_a = prop_rep, #fraction of the population republican
  frac_b = prop_dem, #fraction of the popluation democrat
  time = 150, 
  theta_a = 50, # responsiveness to deaths for republicans adopting protective behavior
  theta_b = 500, # responsiveness to deaths for democrats adopting protective behavior
  theta_c = 110, # responsiveness to deaths for independent adopting protective behavior
  epsilon = 0.5, 
  omega_a = 0.1, # responsiveness to proportion of protected republicans for adopting protective behavior
  omega_b = 0.1, # responsiveness to proportion of protected democrats for adopting protective behavior
  omega_c = 0.1, # responsiveness to proportion of protected independents for adopting protective behavior
  get_params = TRUE
)

sim <- ls$sim
sim$total_infections <- (sim$IUc + sim$IPc) + (sim$IUb + sim$IPb) + (sim$IUa + sim$IPa)
sim <- sim %>%
  mutate(Total = (IUc + IPc) * .00006 + (IUb + IPb) * .00005 + (IUa + IPa) * .00005)

crossing_point <- sim %>%
  filter(Total >= 200) %>%
  slice(1)

# Plot the results
library(ggplot2)
ggplot(sim) +
  geom_line(aes(x = time, y = (IUa + IPa), color = "Republicans"), size = 1) + 
  geom_line(aes(x = time, y = (IUb + IPb), color = "Democrats"), size = 1) + 
  geom_line(aes(x = time, y = (IUc + IPc), color = "Independents"), size = 1) + 
  ylab("Infected Individuals") + 
  xlab("Time (days)") + 
  ggtitle("Prevalence by Party") +
  scale_y_continuous(labels = scales::comma) +
  scale_color_manual(values = c("Republicans" = "red", "Democrats" = "blue", "Independents" = "darkgreen")) +
  theme_minimal() +
  theme(axis.text = element_text(size = 12), 
        axis.title = element_text(size = 14), 
        legend.title = element_blank())

# https://archive.cdc.gov/www_cdc_gov/coronavirus/2019-ncov/cases-updates/burden.html
# Extract the crossing point details
crossing_time <- crossing_point$time
crossing_value <- round(crossing_point$Total, 2)

# Create the plot
ggplot(sim) +
  geom_line(aes(x = time, y = (IUa + IPa) * .00006, color = "Republicans"), size = 1) + 
  geom_line(aes(x = time, y = (IUb + IPb) * .00006, color = "Democrats"), size = 1) + 
  geom_line(aes(x = time, y = (IUc + IPc) * .00006, color = "Independents"), size = 1) + 
  geom_line(aes(x = time, y = Total, color = "Total"), size = 1) + 
  geom_hline(yintercept = 200, linetype = "dashed", color = "black") +
  geom_vline(xintercept = crossing_time, linetype = "dotted", color = "black") + 
  ylab("Hospitalized Individuals") + 
  xlab("Time (days)") + 
  ggtitle("Hospitalizations by Party") +
  labs(subtitle = paste("Total crosses 200 at day =", crossing_time, "with value =", crossing_value)) +
  scale_y_continuous(labels = scales::comma) +
  scale_color_manual(values = c("Republicans" = "red", "Democrats" = "blue", "Independents" = "darkgreen", "Total" = "darkgray")) +
  theme_minimal() +
  theme(axis.text = element_text(size = 12), 
        axis.title = element_text(size = 14), 
        legend.title = element_blank())
```

```{r}
library(shiny)
library(ggplot2)
library(dplyr)

#three types of polarization
#1. Absolute Inverse Polarization: rates of contact, mask usage, etc, grow further apart un-bound
#2. Relative Inverse Polarization: rates of contact, mask usage, etc, grow further apart but overall overage rates stay the same
#3. Uni-directional Polarization: rates of contact, mask usage, etc, grow only for republicans

ui <- fluidPage(
  titlePanel("SIR Model by Party"),
  
  sidebarLayout(
    sidebarPanel(
      numericInput("absolute_polarization", "Absolute Inverse Polarization", 1, min = 1, max = 10, step = 1),
      numericInput("relative_polarization", "Relative Inverse Polarization", 0, min = 0, max = 1, step = .1),
      #numericInput("rep_cc", "Republican Contact Rates:", 4, min = 1, max = 10, step = 0.25),
      #numericInput("dem_cc", "Democrat Contact Rates:", 4, min = 1, max = 10, step = 0.25),
      #numericInput("ind_cc", "Independent Contact Rates:", 4, min = 1, max = 10, step = 0.25),
      numericInput("hospitalization_rate", "Hospitalization Rate", .00006, min = .00001, max = .001, step = .00001),
      numericInput("trans_p", "Transmission Probability:", 0.1, min = 0, max = 1, step = 0.01),
      numericInput("rho", "Recovery Rate (1/Days):", 1/14, min = 0, max = 1, step = 0.01),
      #numericInput("mu", "Death Rate:", 0.01, min = 0, max = 1, step = 0.01),
      numericInput("h_a", "Proportion of Republican Contact within Group:", 0.5, min = 0, max = 1, step = 0.01),
      numericInput("h_b", "Proportion of Democrat Contact within Group:", 0.5, min = 0, max = 1, step = 0.01),
      numericInput("kappa", "Infection Rate:", 0.3, min = 0, max = 1, step = 0.01),
      numericInput("phi", "Recovery Rate after Infection:", 0.02, min = 0, max = 1, step = 0.01),
      numericInput("I0_a", "Initial Infected Republicans:", 1, min = 0, max = 100, step = 1),
      numericInput("I0_b", "Initial Infected Democrats:", 1, min = 0, max = 100, step = 1),
      numericInput("I0_c", "Initial Infected Independents:", 1, min = 0, max = 100, step = 1),
      numericInput("N0", "Total Population:", 7753000, min = 0, max = 1e10, step = 1000),
      numericInput("prop_rep", "Fraction of Population Republican:", 0.33, min = 0, max = 1, step = 0.01),
      numericInput("prop_dem", "Fraction of Population Democrat:", 0.33, min = 0, max = 1, step = 0.01),
      numericInput("time", "Time (days):", 150, min = 1, max = 365, step = 1),
      numericInput("theta_a", "Republican Responsiveness to Deaths:", 100, min = 0, max = 500, step = 1),
      numericInput("theta_b", "Democrat Responsiveness to Deaths:", 100, min = 0, max = 500, step = 1),
      numericInput("theta_c", "Independent Responsiveness to Deaths:", 100, min = 0, max = 500, step = 1),
      numericInput("epsilon", "Rate of Behavior Change:", 0.5, min = 0, max = 1, step = 0.01),
      numericInput("omega_a", "Republican Responsiveness to Protective Behavior:", 0.1, min = 0, max = 1, step = 0.01),
      numericInput("omega_b", "Democrat Responsiveness to Protective Behavior:", 0.1, min = 0, max = 1, step = 0.01),
      numericInput("omega_c", "Independent Responsiveness to Protective Behavior:", 0.1, min = 0, max = 1, step = 0.01)
    ),
    
    mainPanel(
      plotOutput("sirPlot")
    )
  )
)

# Define server logic
server <- function(input, output) {
  
  output$sirPlot <- renderPlot({
    # Placeholder function for sir_three_group_pu
    sir_three_group_pu_working <- sir_three_group_pu

    # Run the simulation
    ls <- sir_three_group_pu_working(
      c = NA, 
      c_a = 4 * ((log(input$absolute_polarization) + 1 + input$relative_polarization)) + .00001, # Republican contact rates
      c_b = 4 * ((1 / (log(input$absolute_polarization) + 1) - input$relative_polarization)) + .00001, # Democrat contact rates
      c_c = 4, # Independent contact rates
      trans_p = input$trans_p, 
      rho = input$rho, 
      mu = 0.01, 
      h_a = input$h_a, # Proportion Republican contact with members of their own group
      h_b = input$h_b, # Proportion Democrat contact with members of their own group
      kappa = input$kappa, 
      phi = input$phi, 
      I0_a = input$I0_a, # Initial infected in Republican group
      I0_b = input$I0_b, # Initial infected in Democrat group
      I0_c = input$I0_c, # Initial infected in Independent group
      N0 = input$N0, 
      frac_a = input$prop_rep, # Fraction of the population Republican
      frac_b = input$prop_dem, # Fraction of the population Democrat
      time = input$time, 
      theta_a = input$theta_a, # Responsiveness to deaths for Republicans adopting protective behavior
      theta_b = input$theta_b, # Responsiveness to deaths for Democrats adopting protective behavior
      theta_c = input$theta_c, # Responsiveness to deaths for Independents adopting protective behavior
      epsilon = input$epsilon, 
      omega_a = input$omega_a, # Responsiveness to proportion of protected Republicans for adopting protective behavior
      omega_b = input$omega_b, # Responsiveness to proportion of protected Democrats for adopting protective behavior
      omega_c = input$omega_c, # Responsiveness to proportion of protected Independents for adopting protective behavior
      get_params = TRUE
    )

    sim <- ls$sim
    rep_cc <- ls[["params"]][["c_a"]]
    dem_cc <- ls[["params"]][["c_b"]]
    
    print(names(sim))
    print(str(sim))
    print(summary(sim))
    
    sim <- sim %>%
      mutate(Total = (IUc + IPc) * input$hospitalization_rate + (IUb + IPb) * input$hospitalization_rate + (IUa + IPa) * input$hospitalization_rate,
             hospitalizations = input$hospitalization_rate,
             rep_cc = rep_cc,
             dem_cc = dem_cc,
             total_contacts = rep_cc + dem_cc)
    
    print(head(sim))
    print(table(sim$hospitalization_rate))
    
    crossing_point <- sim %>%
      filter(Total >= 200) %>%
      slice(1)
    
    crossing_time <- crossing_point$time
    crossing_value <- round(crossing_point$Total, 2)
    
    # plot
    ggplot(sim, aes(x = time)) +
      geom_line(aes(y = (IUa + IPa) * input$hospitalization_rate, color = "Republicans"), size = 1) +
      geom_line(aes(y = (IUb + IPb) * input$hospitalization_rate, color = "Democrats"), size = 1) +
      geom_line(aes(y = (IUc + IPc) * input$hospitalization_rate, color = "Independents"), size = 1) +
      geom_line(aes(y = Total, color = "Total"), size = 1) +
      geom_hline(yintercept = 200, linetype = "dashed", color = "black") +
      geom_vline(xintercept = crossing_time, linetype = "dotted", color = "black") + 
      labs(title = "Hospitalizations by Party",
           y = "Hospitalized Individuals",
           x = "Time (days)") +
      scale_y_continuous(labels = scales::comma) +
      labs(subtitle = paste("Hospitals overwhelmed at day =", crossing_time, "with value =", crossing_value, ", republican daily contact = ", round(rep_cc, digits = 2), ", democrat daily contacts = ",round(dem_cc, digits = 2),", total republican and democrat daily contacts: ", round(rep_cc, digits = 2)+round(dem_cc, digits = 2))) +
      scale_color_manual(values = c("Republicans" = "red", "Democrats" = "blue", "Independents" = "darkgreen", "Total" = "darkgray")) +
      theme_minimal() +
      theme(axis.text = element_text(size = 12), 
            axis.title = element_text(size = 14), 
            legend.title = element_blank())
  })
}

# Run the application 
shinyApp(ui = ui, server = server)
```
```{r}
level = 9
delta = 1  # Adjust this value to increase/decrease the gap

# Original values
rep_cc = 4 * (log(level) + 1)
dem_cc = 4 * (1 / (log(level) + 1))
original_sum = rep_cc + dem_cc

# New values with delta
rep_cc_new = 4 * (log(level) + 1 + delta)
dem_cc_new = 4 * (1 / (log(level) + 1) - delta)
new_sum = rep_cc_new + dem_cc_new

# Print results
print(paste("Original rep_cc:", rep_cc))
print(paste("Original dem_cc:", dem_cc))
print(paste("Original sum:", original_sum))
print(paste("New rep_cc:", rep_cc_new))
print(paste("New dem_cc:", dem_cc_new))
print(paste("New sum:", new_sum))
```


```{r}
rm(sf_df, pho_df)
```

