---
title: "Table 1"
author: "Christopher Soria"
date: "2023-11-08"
output: html_document
---

```{r}
library(tidyverse)
library(data.table)
library(dplyr)
library(kableExtra)
library(knitr)
```

```{r}
df <- fread("/Users/chrissoria/Documents/Research/BICS_Political_Polarization/data/BICS_ZIP_Features.csv")
RD_df <- df[df$political_party %in% c("Republican", "Democrat"), ]
D_df <- df[df$political_party == "Democrat"]
R_df <- df[df$political_party == "Republican"]

names(df) <- make.unique(names(df))
names(RD_df) <- make.unique(names(RD_df))
names(D_df) <- make.unique(names(D_df))
names(R_df) <- make.unique(names(R_df))
```

Below, I'm pulling out the non-matches to see if I can find a pattern to address
There are only 71 rows so I will leave it as it is
```{r}
df_na_subset <- df %>% 
  filter(is.na(`rate_prev_6/21/20`))

write.csv(df_na_subset, "../data/no_prev.csv")
```


```{r}
average_by_party <- df %>%
  filter(political_party != "Prefer not to answer") %>% 
  group_by(political_party) %>%
  summarise(
    average_num_cc_nonhh = mean(num_cc_nonhh, na.rm = TRUE),
    average_contact_reduction = mean(contact_reduction, na.rm = TRUE),
    average_concern = mean(binary_concern_strong, na.rm = TRUE),
    average_mask_usage = mean(Norm_Masks_Used, na.rm = TRUE),
    average_safety_index = mean(Non_Weighted_Safety_Index, na.rm = TRUE),
    average_vaccinated = mean(Vaccinated, na.rm = TRUE)
  )

average_by_party_table <- t(as.data.frame(average_by_party))
average_by_party_table <- as.data.frame(average_by_party_table)
average_by_party_table <- average_by_party_table[-1, ]

for (col in 1:3) {
  average_by_party_table[, col] <- as.numeric(as.character(average_by_party_table[, col]))
}

average_by_party_table[, 1:3] <- round(average_by_party_table[, 1:3], digits = 3)

apt_row_names <- c("Non-Household Contacts", "Level of Stated Contact Reduction", "Concern About the Spread of the Virus", "Proportion of Contacts with a Mask", "Overall Safety During Contacts", "Proportion Vaccinated")
rownames(average_by_party_table) <- apt_row_names

kable_output <- kable(average_by_party_table, 
                      caption = "Table 1. Descriptive Outcomes by Political Party",
                      col.names = c("Democrat", "Independent", "Republican"),
                      align = c("c", "c", "c"))

# Add a horizontal line after the first row
kable_styled <- kable_output %>%
  kable_styling() %>%
  add_header_above(c(" " = 1, "Political Parties" = 3)) %>%  # Optional: Add a header above the column names
  pack_rows(index = c("Average Reported Raw Counts" = 1, "Proportions" = 5))

print(kable_styled)

rm(average_by_party)
```

```{r}
average_by_candidate <- D_df %>%
  filter(Categorical_Repub_CD_County_Share != "") %>% 
  group_by(Categorical_Repub_CD_County_Share) %>%
  summarise(
    average_num_cc_nonhh = mean(num_cc_nonhh, na.rm = TRUE),
    average_contact_reduction = mean(contact_reduction, na.rm = TRUE),
    average_concern = mean(binary_concern_strong, na.rm = TRUE),
    average_mask_usage = mean(Norm_Masks_Used, na.rm = TRUE),
    average_safety_index = mean(Non_Weighted_Safety_Index, na.rm = TRUE),
    average_vaccinated = mean(Vaccinated, na.rm = TRUE)
  )

average_by_candidate_table <- t(as.data.frame(average_by_candidate))
average_by_candidate_table <- as.data.frame(average_by_candidate_table)
average_by_candidate_table <- average_by_candidate_table[-1, -1]

for (col in 1:3) {
  average_by_candidate_table[, col] <- as.numeric(as.character(average_by_candidate_table[, col]))
}

average_by_candidate_table[, 1:3] <- round(average_by_candidate_table[, 1:3], digits = 3)

apt_row_names <- c("Non-Household Contacts", "Level of Stated Contact Reduction", "Concern About the Spread of the Virus", "Proportion of Contacts with a Mask", "Overall Safety During Contacts", "Proportion Vaccinated")
rownames(average_by_candidate_table) <- apt_row_names

kable_output <- kable(average_by_candidate_table, 
                      caption = "Table 2. Descriptive Outcomes for Democrats by Republican Vote Share",
                      col.names = c("Overwhelming Majority Voted Repub", "Significant Repub Support", "Minority Repub Support"),
                      align = c("c", "c", "c"))

# Add a horizontal line after the first row
kable_styled <- kable_output %>%
  kable_styling() %>%
  add_header_above(c(" " = 1, "Democrat Behavior According to Percentage of County Voted Repub" = 3)) %>%  # Optional: Add a header above the column names
  pack_rows(index = c("Counts" = 1, "Proportions" = 5))

print(kable_styled)

print(average_by_candidate)
rm(average_by_candidate)
```

```{r}
average_by_candidate <- R_df %>%
  filter(Categorical_Dem_CD_County_Share != "") %>% 
  group_by(Categorical_Dem_CD_County_Share) %>%
  summarise(
    average_num_cc_nonhh = mean(num_cc_nonhh, na.rm = TRUE),
    average_contact_reduction = mean(contact_reduction, na.rm = TRUE),
    average_concern = mean(binary_concern_strong, na.rm = TRUE),
    average_mask_usage = mean(Norm_Masks_Used, na.rm = TRUE),
    average_safety_index = mean(Non_Weighted_Safety_Index, na.rm = TRUE),
    average_vaccinated = mean(Vaccinated, na.rm = TRUE)
  )

average_by_candidate_table <- t(as.data.frame(average_by_candidate))
average_by_candidate_table <- as.data.frame(average_by_candidate_table)
average_by_candidate_table <- average_by_candidate_table[-1, -1]

for (col in 1:3) {
  average_by_candidate_table[, col] <- as.numeric(as.character(average_by_candidate_table[, col]))
}

average_by_candidate_table[, 1:3] <- round(average_by_candidate_table[, 1:3], digits = 3)

apt_row_names <- c("Non-Household Contacts", "Level of Stated Contact Reduction", "Concern About the Spread of the Virus", "Proportion of Contacts with a Mask", "Overall Safety During Contacts", "Proportion Vaccinated")
rownames(average_by_candidate_table) <- apt_row_names

kable_output <- kable(average_by_candidate_table, 
                      caption = "Table 2. Descriptive Outcomes for Republicans by Democrat Vote Share",
                      col.names = c("Overwhelming Demo Support", "Significant Dem Support", "Minority Dem Support"),
                      align = c("c", "c", "c"))

# Add a horizontal line after the first row
kable_styled <- kable_output %>%
  kable_styling() %>%
  add_header_above(c(" " = 1, "Republican Behavior According to Percentage of County Voted Democrat" = 3)) %>%  # Optional: Add a header above the column names
  pack_rows(index = c("Counts" = 1, "Proportions" = 5))

print(kable_styled)

print(average_by_candidate)
rm(average_by_candidate)
```

